# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14
  env:
    global:
      - CODECOV_TOKEN="4b630805-08db-4cfc-8e93-aceef5825ee1"
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту goncharikvv@gmail.com если сборка упала
notifications:
  email:
    recipients:
      -goncharikvv@gmail.com
    on_success: never # default: change
    on_failure: always # defa,ult: always

